---
title:    'Exploring US COVID-19 Cases and Deaths'
subtitle: 'Our World in Data - Data Sets'
author:   'H. David Shea'
date: 2021-04-20
output:
    pdf_document: default
---

```{r setup, include = FALSE}
library(tidyverse)
library(rvest)
library(timetk)
library(lubridate)
library(broom)
library(knitr)
library(httr)

knitr::opts_chunk$set(
    connection = "secdb", # automatically uses this connection in sql chunks 
    comment = "#>", 
    collapse = TRUE, 
    message = FALSE,
    fig.width = 8,
    fig.asp = ((1 + sqrt(5)) / 2) - 1, # the golden ratio - technically, the b proportion of a+b when a is 1
    out.width = "70%",
    fig.align = "center"
)
```

## Our World in Data (OWID) COVID-19 Data

This analysis uses the Our World in Data COVID-19 data sets.  These are available at the [_OWID GitHub site_](https://covid.ourworldindata.org/).

```{r rawdata, include = TRUE, warning = FALSE, echo = FALSE}
# source https://covid.ourworldindata.org/

# OWID Corona Virus data
owid_full_metadata_url <- "https://covid.ourworldindata.org/data/owid-covid-codebook.csv"
owid_full_dataset_url <- "https://covid.ourworldindata.org/data/owid-covid-data.csv"

# Get metadata
owid_full_metadata <- tibble(read.csv(owid_full_metadata_url))

# Get the actual data
owid_full_dataset <- tibble(read.csv(owid_full_dataset_url)) %>%
  mutate(date = as.Date(date)) %>%
  arrange(location, date)
```

## Exploratory Data Analyses

### World Cases versus Deaths

```{r global_cases_and_deaths, include = TRUE, warning = FALSE, echo = FALSE}
coeff <- 30
owid_full_dataset %>%
  filter(location == "World") %>% 
  ggplot(aes(date, new_cases_smoothed)) +
  geom_line(color = "orange") +
  theme(legend.position = "none") +
  geom_line(aes(x = date, y = new_deaths_smoothed * coeff), color = "red") +
  scale_y_continuous(
    labels = scales::comma,
    name = "Cases",
    sec.axis = sec_axis(new_deaths_smoothed ~ . / coeff,
      name = "Deaths",
      labels = scales::comma
    )
  ) +
  theme(
    axis.title.y = element_text(color = "orange", size = 13),
    axis.title.y.right = element_text(color = "red", size = 13)
  ) +
  labs(
    title = "World Cases vs. Deaths",
    subtitle = "7-Day Smoothed",
    caption = "Source:  Our World in Data",
    x = "Date"
  )
```

### US Cases versus Deaths

```{r us_cases_and_deaths, include = TRUE, warning = FALSE, echo = FALSE}
coeff <- 30
owid_full_dataset %>%
  filter(location == "United States") %>% 
  ggplot(aes(date, new_cases_smoothed)) +
  geom_line(color = "orange") +
  theme(legend.position = "none") +
  geom_line(aes(x = date, y = new_deaths_smoothed * coeff), color = "red") +
  scale_y_continuous(
    labels = scales::comma,
    name = "Cases",
    sec.axis = sec_axis(new_deaths_smoothed ~ . / coeff,
      name = "Deaths",
      labels = scales::comma
    )
  ) +
  theme(
    axis.title.y = element_text(color = "orange", size = 13),
    axis.title.y.right = element_text(color = "red", size = 13)
  ) +
  labs(
    title = "U.S. Cases vs. Deaths",
    subtitle = "7-Day Smoothed",
    caption = "Source:  Our World in Data",
    x = "Date"
  )
```

### Global Regions

```{r region_cases_and_deaths, include = TRUE, warning = FALSE, echo = FALSE}
regions <- c("Africa", "Asia", "Europe", "North America", "Oceania", "South America")

owid_full_dataset %>%
  filter(location %in% regions) %>% 
  ggplot(aes(date, new_cases_smoothed / 1000, color = location)) +
  geom_line() +
  theme(legend.position = "bottom") +
  labs(
    title = "Cases by Region",
    caption = "Source:  Our World in Data",
    color = "Region",
    x = "Date",
    y = "7-Day Smoothed (000)"
  )
owid_full_dataset %>%
  filter(location %in% regions) %>% 
  ggplot(aes(date, new_deaths_smoothed, color = location)) +
  geom_line() +
  theme(legend.position = "bottom") +
  labs(
    title = "Deaths by Region",
    caption = "Source:  Our World in Data",
    color = "Region",
    x = "Date",
    y = "7-Day Smoothed"
  )
```

### Current Problem Areas
```{r problem_areas, include = TRUE, warning = FALSE, echo = FALSE}
top_50_pop <- owid_full_dataset %>%
  filter(date == (max(unique(owid_full_dataset$date)) - 1)) %>%
  filter(!str_starts(iso_code, "OWID")) %>%
  arrange(desc(population)) %>%
  filter(row_number() <= 50) %>%
  pull(location)

top_6_change_cases <- owid_full_dataset %>%
  filter(date >= (max(unique(owid_full_dataset$date)) - 35)) %>%
  filter(location %in% top_50_pop) %>%
  mutate(
    cases_change = round(total_cases / lag(total_cases, 30), 2),
    deaths_change = round(total_deaths / lag(total_deaths, 30),2)
    ) %>%
  filter(date == (max(unique(owid_full_dataset$date)) - 1)) %>%
  select(location, date, cases_change, deaths_change) %>%
  arrange(desc(cases_change)) %>%
  filter(row_number() <= 6)

top_6_change_deaths <- owid_full_dataset %>%
  filter(date >= (max(unique(owid_full_dataset$date)) - 35)) %>%
  filter(location %in% top_50_pop) %>%
  mutate(
    cases_change = total_cases / lag(total_cases, 30),
    deaths_change = total_deaths / lag(total_deaths, 30)
  ) %>%
  filter(date == (max(unique(owid_full_dataset$date)) - 1)) %>%
  select(location, date, cases_change, deaths_change) %>%
  arrange(desc(deaths_change)) %>%
  filter(row_number() <= 6)
```

#### Countries with Highest Change in Cases Over the Past Month

```{r problem_areas_cases, include = TRUE, warning = FALSE, echo = FALSE}
top_6_change_cases %>% kable()

owid_full_dataset %>%
  filter(location %in% (top_6_change_cases %>% pull(location))) %>%
  ggplot(aes(date, new_cases_smoothed / 1000)) +
  geom_line() +
  facet_wrap(~location, scales = "free") +
  theme(legend.position = "bottom") +
  labs(
    title = "Cases by Region",
    caption = "Source:  Our World in Data",
    x = "Date",
    y = "7-Day Smoothed Cases (000)"
  )
```

#### Highest Change in Deaths Over the Past Month

```{r problem_areas_deaths, include = TRUE, warning = FALSE, echo = FALSE}
top_6_change_deaths %>% kable()

owid_full_dataset %>%
  filter(location %in% (top_6_change_deaths %>% pull(location))) %>%
  ggplot(aes(date, new_deaths_smoothed)) +
  geom_line() +
  facet_wrap(~location, scales = "free") +
  theme(legend.position = "bottom") +
  labs(
    title = "Deaths by Region",
    caption = "Source:  Our World in Data",
    x = "Date",
    y = "7-Day Smoothed Deaths"
  )
```
